[hardening_servers]
localhost ansible_connection=local

# AWS EC2 Cloud execution (via AWS Systems Manager)
[aws_hardening_targets]
i-037ff79be19ce2ed8

[aws_hardening_targets:vars]
ansible_connection=community.aws.aws_ssm
ansible_aws_ssm_region=us-east-1
ansible_aws_ssm_bucket_name="ansible-ssm-staging-42d5cb10"
ansible_aws_ssm_role_name="ansible-ssm-role"
ansible_user=ssm-user
ansible_become=true
ansible_python_interpreter=/usr/bin/python3